[tool.poetry]
name = "rag-chroma"
version = "0.1.0"
description = "RAG using Chroma"
authors = [
    "Erick Friis <erick@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
langchain = ">0.1"
openai = ">=0.1.0"
tiktoken = ">=0.5.1"
chromadb = ">=0.4.14"
langchain-google-community = {extras = ["drive"], version = "^2.0.2"}
langchain-openai = "^0.2.5"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "rag_chroma"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "Chroma"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
